# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160117_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to='/carousel'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='editor_choice',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='editor_choice',
            field=models.CharField(default='tinyMCE', max_length=20),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
